Alter files and license header
ZK-Garage/plonk pull request #63
Opened 2021-12-17 07:06 UTC by LukePearson1

This solves #62

2021-12-17 09:42 UTC, CPerezz requested changes
All OK.

But i would prefer to keep the example in the README. Otherways, cargo can not check the correctnesd of the example while running the tests.

2021-12-17 15:58 UTC, bhgomes commented
> But i would prefer to keep the example in the README. Otherways, cargo can not check the correctnesd of the example while running the tests.

The test is in the source already.

2021-12-18 09:21 UTC, bhgomes commented
@LukePearson1 If you add a file called `.rustfmt.toml` and add the line

```
license_template_path = "FILE_TEMPLATE"
```

and then create a file called `FILE_TEMPLATE` and add the header you've added to every file in the repo to this file, then `rustfmt` will do a check that all the source code files have the correct copyright header.

2021-12-18 12:31 UTC, davidnevadoc approved these changes

2021-12-19 22:51 UTC, bhgomes approved these changes

2021-12-20 09:46 UTC, merged