Update and Extend Documentation
ZK-Garage/plonk pull request #91
Opened 2022-01-19 10:06 UTC by markulf

Starting with broken links. But any other kind of documentation is also welcome. 
Might by its very nature. Documentation is never finished be broken up into multiple pull requests.

2022-01-19 10:19 UTC, CPerezz commented
I highly reccomend you to look at https://keepachangelog.com/en/1.0.0/ in order to add a CHANGELOG.

Anyway, since we will start on 0.1, we will just start mantaining it after that. Otherways there's A LOT of PR's to take into account.

2022-01-19 12:04 UTC, markulf commented
> I highly reccomend you to look at https://keepachangelog.com/en/1.0.0/ in order to add a CHANGELOG.
> 
> Anyway, since we will start on 0.1, we will just start mantaining it after that. Otherways there's A LOT of PR's to take into account.

Makes sense, probably still better to have a stub there than a broken link. Added a comment that we start this process from version 0.1.

2022-01-25 23:28 UTC, markulf reviewed
The title should be plonk-core/src/lib.rs

Likely these includes should just be removed and the files deleted.

2022-01-26 10:59 UTC, CPerezz reviewed
Looks good. 

We might add a bit simpler examples IMO. Or group them by:
- Arith
- Bool
- ECC
- Range
- Misc

2022-01-26 10:59 UTC, CPerezz commented on examples/simple_circuit.rs
> +}
Add new line at the end of the file

2022-01-26 10:59 UTC, CPerezz commented on examples/simple_circuit.rs
> +//use ark_ec::{PairingEngine, TEModelParameters};
Remove the commented stuff

2022-01-27 15:30 UTC, markulf commented
Closing this. Too many small building sites for one pull request.

2022-01-27 21:08 UTC, LukePearson1 approved these changes
LGTM! 

Had to so some merging to get up to date with the latest branch.

2022-01-27 22:15 UTC, bhgomes requested changes

2022-01-27 22:15 UTC, bhgomes commented on examples/simple_circuit.rs
> +use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
@LukePearson1 still need to remove this line

2022-01-27 22:16 UTC, bhgomes approved these changes

2022-01-27 22:48 UTC, merged

2022-01-28 08:18 UTC, CPerezz commented
@bhgomes @LukePearson1 This PR started to make the `intra-doc links` fail. 

Why was it merged?

2022-01-28 13:59 UTC, bhgomes commented
> @bhgomes @LukePearson1 This PR started to make the `intra-doc links` fail. 
> 
> 
> 
> Why was it merged?

We don't know how the intra-doc links are broken since this PR doesn't seem to change anything related to that.