Compile book instructions
ZK-Garage/plonk pull request #93
Opened 2022-01-24 10:27 UTC by mathcrypto

2022-01-24 10:40 UTC, CPerezz commented
@mathcrypto Can you rebase on top of `main` so that the history is not massive??
Otherways there are an insane amount of commits because you're re-using the same branch for different PR's.

2022-01-24 10:44 UTC, CPerezz requested changes
Benchmark section in `chapter3.md` has inconsistent processor descriptions.

I suggest to take them from the actual README where the exact model is stated.

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/SUMMARY.md
> +- [Chapter 3: ARK-PLONK library](./chapter_3.md)
I'd leave as `PLONK` for now :)

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +# ARK-PLONK library
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +ARK-PLONK is however the only generic implementation which allows any curve implementation or commitment scheme to be used and isn’t restricted to only one implementation like other existing librarie
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +ARK-PLONK is an optimization of the original PLONK protocol and guarantees $3.44s$ for proving time and $4.50ms$ for verifier speed comparing to $60$ proof times in the original PLONK design.
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +The different types of gates in Ark-plonk are:
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +ARK-PLONK's implementation is an optimization of the original PLONK protocol as it enables lookup table to the PLONK circuit. This optimization allows for precomputation of some of the operations tha
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +Ark-plonk gates on the other hand are fan-in-3 gates, so they have one more wire which makes it 4 wires in total.
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +Ark-plonk still allows the use of fan-in 2 gates only by setting the 4th wire selector $q_d$ to $0$.
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +Ark-plonk logic gates can perform bitwise AND and XOR operations.
ditto

2022-01-24 10:44 UTC, CPerezz commented on plonk-book/src/chapter_3.md
> +In ARK-PLONK, we use PlonKup, a ZK-SNARK that integrates plookup into PlonK in an efficient way. Before we explain how PlonKup works, we will introduce the original [plookup]((https://eprint.iacr.org
ditto

2022-01-24 10:46 UTC, mathcrypto commented on plonk-book/src/SUMMARY.md
> +- [Chapter 3: ARK-PLONK library](./chapter_3.md)
Of course :)

2022-01-24 10:47 UTC, mathcrypto commented
> Benchmark section in `chapter3.md` has inconsistent processor descriptions.
> 
> I suggest to take them from the actual README where the exact model is stated.

will leave them out of chapter 3 then

2022-01-24 12:42 UTC, mathcrypto commented
> 

On top of Master?

2022-01-24 12:43 UTC, mathcrypto commented
> @mathcrypto Can you rebase on top of `main` so that the history is not massive?? Otherways there are an insane amount of commits because you're re-using the same branch for different PR's.

On top of Master?

2022-01-24 13:40 UTC, CPerezz commented
@mathcrypto yes sorry. `master` correct!!

2022-01-27 02:42 UTC, LukePearson1 reviewed
Will merge this, with a squash into 1 commit. 

The failing docs-link is noted in #96

2022-01-27 02:52 UTC, merged